[package]
name = "vamp-ir"
version = "0.1.0"
edition = "2021"

[features]
# Enable Standard Library
std = []

[dependencies]
pest = "2.1.0"
pest_derive = "2.1.0"
pest-ast = "0.3.3"
from-pest = "0.3.1"
ark-ff = "0.3.0"
lazy_static = "1.3.0"
